### ISSUE TITLE
Location comments toggle

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#511]
When toggling location contacts for 'HIDE' and 'VIEW', location Comments toggle will also change from HIDE and VIEW (comment does not open, but the 'hide/view' changes.)

Test Version 2.0.0-beta.9

**Comment by BlakeDraper** [comment]
Done in code (user-events-pagination branch)

**Comment by BlakeDraper** [comment]
Done with #514

**Comment by JChipault** [comment]
Still an issue with location contacts and location comments in v2.3.0. This is event 200045. At one point, both contacts and comments were condensed but both said "Hide" on the bar. After I toggle open and then toggle closed, they appropriately read "view".
![image](https://user-images.githubusercontent.com/49287076/62981589-35441b00-bdef-11e9-9a84-a77b2a5033a9.png)

**Comment by JChipault** [comment]
@BlakeDraper and @lprivette Still an issue in 2.5.0. Can we reopen this issue?
Saw something like this a couple of times while thumbing through the locations in 200112
![image](https://user-images.githubusercontent.com/49287076/65530024-d2997100-debc-11e9-8a6f-844d788143cf.png)

**Comment by lprivette** [comment]
Thanks for catching @JChipault. We figured out what's causing it and will include a fix for it in the next round of fixes.

**Comment by BlakeDraper** [comment]
Fixed in code.

**Comment by JChipault** [comment]
@lprivette this one keeps creeping back. Was looking at 2.7.1 and saw this
![image](https://user-images.githubusercontent.com/49287076/67436954-4f4f6600-f5b5-11e9-82a6-54e2654f8d40.png)

**Comment by lprivette** [comment]
I'm trying to recreate it now, but not having any luck. Which event are you on in that screenshot? and is it happening seemingly at random or are you able to recreate it?

**Comment by JChipault** [comment]
I think it was event 170782. Seems random. I've been clicking around today and can't get it to recreate.

**Comment by lprivette** [comment]
I got it to recreate when expanding one of the panels > clicking the the comments timeline tab > clicking back to the Event data tab.

Fix incoming

**Comment by lprivette** [comment]
Done in branch `511`.

Also in branch `511` I reverted the accent theme color and styled the mat-tab-group bar with css.

**Comment by JChipault** [comment]
@lprivette This one just keeps manifesting... I'm in 2.8.2 and if an event has multiple locations, and i view comments at one location, when I go to the other location, it has it has "hide" even though it's already hidden. basically the same banner is showing for both locations even if I have comments open at one location and closed at the other. this is event 200124
![image](https://user-images.githubusercontent.com/49287076/68505893-f840c680-022d-11ea-8638-ed789ccb043c.png)

**Comment by JChipault** [comment]
![image](https://user-images.githubusercontent.com/49287076/68505979-2920fb80-022e-11ea-900b-afc86b46a323.png)

**Comment by BlakeDraper** [comment]
@lprivette is this still outstanding?

**Comment by lprivette** [comment]
Yes. Should I work on this today or stay on reports?

**Comment by BlakeDraper** [comment]
Reports please. I'll look into this.

**Comment by JChipault** [comment]
We talked about this briefly at today's meeting, but here's the email that Neil and I received from Barb (epi) on Monday at 10:16am
Between late last week and again this morning, I have encountered snaffu with "location comment" field. When I enter a new comment and click "add comment" it saves the comment but the "location comment" field then closes. When I try to add another comment, I have to click open the "view comment" field but it does nothing...

**Comment by JChipault** [comment]
@lprivette @BlakeDraper Unfortunately, this is happening again. I looked over Barb's shoulder just now. She opens an event, goes to location comments, adds a comment, and all that works fine. But when she tries to go back and see the comment (or add additional comments to that location), clicking the header for location comments just makes it dance a bit and toggle back and forth between "view" and "hide" but nothing further displays (i.e., it's always collapsed). When she refreshed the web page, it then allowed her to expand that location comments section and add another comment... but then she'd run into the same issue if she wanted to add an additional comment.

**Comment by JChipault** [comment]
Happens with the location contacts as well.

**Comment by JChipault** [comment]
also, sometimes the location contacts "add contact" subform will open, but nothing happens when I click the "contact person" line. It's acting similar to how the staff list was behaving a couple of weeks ago. No drop down appears. However, if i refresh the web page and open it back up, it works.

**Comment by lprivette** [comment]
@BlakeDraper I started playing with a fix on branch `511`. I've only added the fix to the location comments panels. I found this example which I followed: https://stackblitz.com/edit/angular-expansion-panel-toggle-header?file=app%2Fexpansion-overview-example.html

It works better than what's in test/production currently, but eventually returns to the old/wrong behavior after different parent (i think) expansion panel headers are clicked. 

I think the issue is that we don't use an ngFor on the comments/contact panels, so the index that is set in the eventlocation (where the ngfor is) is tied to the parent expansion panel click which is not what we need, if that makes sense.

**Comment by BlakeDraper** [comment]
I've discovered a fix, but it _may_ have side effects that I am not seeing right now. For one thing, I set the open/closed variable for each comments collapse pane and contacts collapse pane to `eventLocation.commentsOpen` and `eventLocation.contactsOpen`, respectively. The `eventLocation` is in the context of the `*ngFor` at the parent level: `*ngFor="let eventLocation of eventData.eventlocations; let i = index"` which makes each one the unique instance of the eventLocation. So that works, but then the reported problem was still happening once submitting a new comment or contact. So that pointed me to something wrong within the `refreshEvent()` function. I was curious about the `getViewPanelState()` and `setViewPanelState()` functions. Commenting them out fixes the problem, and I am not seeing any ill-effects after several tests. I don't remember why I wrote these or if it was even me. I wonder if they were  created in a much earlier version of the eventDetails component and were needed for panel refreshing at the time. I believe something was restructured in the meantime, making them unnecessary. 

@lprivette or @njestes do you have any better memory on these functions and whether they are actually needed for something I am not detecting? If not, I will ship this as the fix.

**Comment by lprivette** [comment]
Nice! 

I'm not familiar with those functions.

**Comment by JChipault** [comment]
Looks like it's working in v2.11.0!!! Nice!

**Comment by BlakeDraper** [comment]
Published and confirmed fixed in v2.11.0.

**Comment by JChipault** [comment]
@BlakeDraper Maybe a reversion happened on this one??  Saw this just now on the live site v2.15.10, event 201002. Unfortunately, I don't remember the sequence of steps before this appeared and can't easily re-create it. But posting here in case you can see some previous fix that got lost.

![image](https://user-images.githubusercontent.com/49287076/107577546-30188580-6bb8-11eb-9073-e2ecd5539328.png)

**Comment by JChipault** [comment]
I seem to have lost my ability to re-open github tickets but we might want to re-open this one
