### ISSUE TITLE
Null event diagnosis

### ISSUE THREAD

**Issue by nbaertlein** [USGS-WiM/whispers#536]
Can delete event diagnosis so that no event diagnosis can be found (violates business rules).   

Selection of null diagnosis, "--",  causes error upon saving.  Should we remove null option?

See https://whispersbeta.wim.usgs.gov/test/whispers/event/170710

**Comment by BlakeDraper** [comment]
yes, remove null option

**Comment by BlakeDraper** [comment]
done in code

**Comment by JChipault** [comment]
@BlakeDraper - v13 does indeed remove "--" from dropdown but other part of this ticket does not seem to be resolved in that I can still be on Event Details page and remove all event diagnoses and thus have nothing listed for Event Diagnosis.

**Comment by JChipault** [comment]
@BlakeDraper Still an issue with v15 in that you can remove all event diagnoses on the event details page and have the event diagnosis be blank then on the home page table. Should be labeled as Pending or Undetermined (depending on WHISPers Record Status) if user manually removes other event diagnoses.
