### ISSUE TITLE
type ahead gone when edit state or county

### ISSUE THREAD

**Issue by JChipault** [USGS-WiM/whispers#617]
On event details page, type ahead feature gone if I edit the state or county

**Comment by BlakeDraper** [comment]
It's not gone, rather it never was implemented for the edit event location details component. Can add.

**Comment by BlakeDraper** [comment]
Done in code

**Comment by JChipault** [comment]
@BlakeDraper whoops... now when I click "Edit Event Location Details" state and county are always blank when the subform pops up even though they were entered when the event was created

**Comment by JChipault** [comment]
@BlakeDraper Keeping this one on the radar because still an issue in v2.3.0

**Comment by lprivette** [comment]
Fixed this by removing the `toString()` during the form patchValue. I don't understand why it wasn't working with the toString() though tbh.

Done in branch `617`.

**Comment by BlakeDraper** [comment]
Look good. merged in my local dev branch.

**Comment by JChipault** [comment]
looks good
